name = "ArealInterpolation"
uuid = "d0f2625a-dce2-41fa-8f52-900cefdd6e0e"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com> and contributors"]
version = "0.0.1-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
